gui:
  showCommandLog: false
  showIcons: false
  theme:
    selectedLineBgColor:
      - reverse

os:
  edit: "code {{filename}}"
  open: "code {{filename}}"

git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
