#################
### AUTOSTART ###
#################
exec-once = waybar
exec-once = hyprpaper
exec-once = ~/.config/hypr/scripts/wallpaper_startup.sh
exec-once = wl-paste --watch cliphist store
exec-once = cliphist wipe
exec-once = hypridle
