-- Generated by nwg-displays on 2026-05-31 at 19:59:53. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.01",
    position = "0x0",
    scale = 0.9999999999999997
})
