# Remap send-prefix to ^a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Remap new window to prefix+n
unbind c
unbind n
bind-key N new-window
bind-key n new-window -c "#{pane_current_path}"

set -g @plugin 'sainnhe/tmux-fzf'
TMUX_FZF_LAUNCH_KEY="C-l"
bind-key "f" run-shell -b "~/.config/tmux/plugins/tmux-fzf/scripts/pane.sh switch"
bind-key "s" run-shell -b "~/.config/tmux/plugins/tmux-fzf/scripts/session.sh switch"

bind-key "e" run-shell -b "~/.config/tmux/plugins/tmux-fzf/scripts/session.sh"
bind-key "w" run-shell -b "~/.config/tmux/plugins/tmux-fzf/scripts/window.sh"

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
