# Renumber windows
set-option -g renumber-windows on

# max session name length
set -g status-left-length 50

set-option -g status-interval 1
set-option -g automatic-rename on
set-option -g automatic-rename-format "#{?#{==:#{pane_current_command},#{b:SHELL}},#{b:pane_current_path},#{pane_current_command}}"

# Remap send-prefix to ^a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Remap new window to prefix+n
unbind c
unbind n
bind-key N new-window
bind-key n new-window -c "#{pane_current_path}"

unbind o
bind-key o last-window

set -g @plugin 'sainnhe/tmux-fzf'

TMUX_FZF_LAUNCH_KEY="w"
TMUX_FZF_ORDER="session|window"
TMUX_FZF_OPTIONS="-p -w 95% -h 90% -m --preview-window=right:50%:wrap"

TMUX_FZF_PANE_FORMAT="[#{window_name}] #{window_flags} #{s/#{HOME}/~/:pane_current_path}"
TMUX_FZF_WINDOW_FORMAT="[#{window_name}] #{window_flags} #{s/#{HOME}/~/:pane_current_path}"

bind-key -T prefix f run-shell "bash ${HOME}/.config/tmux/scripts/window_current_session.sh switch"

bind-key "a" run-shell -b "~/.config/tmux/plugins/tmux-fzf/scripts/window.sh switch"
bind-key "s" run-shell -b "~/.config/tmux/plugins/tmux-fzf/scripts/session.sh switch"

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
