# Renumber windows
set-option -g renumber-windows on

# max session name length
set -g status-left-length 50

set-option -g status-interval 1
set-option -g automatic-rename on
set-option -g automatic-rename-format "#{?#{==:#{pane_current_command},#{b:SHELL}},#{b:pane_current_path},#{pane_current_command}}"

# Remap send-prefix to ^a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Remap new window to prefix+n
unbind n
unbind c
bind-key n new-window -c "#{pane_current_path}"

unbind o
bind-key o last-window

unbind w
bind-key w bind-key w choose-session

unbind s
bind s display-popup -E "~/.config/tmux/scripts/tmux-session-startup-and-switch.sh"
bind S display-popup -E "~/.config/tmux/scripts/tmux-session-switch.sh"
bind-key -T prefix f run-shell "bash ${HOME}/.config/tmux/scripts/window_current_session.sh switch"

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
